"""Render the v0.1 data-quality report from machine-readable artifacts."""

from __future__ import annotations

from pathlib import Path
from typing import Any


def _integer(value: int | float) -> str:
    return f"{int(value):,}"


def _number(value: int | float) -> str:
    return f"{float(value):,.2f}"


def _percent(value: int | float) -> str:
    return f"{float(value) * 100:.4f}%"


def _size(size_bytes: int) -> str:
    return f"{size_bytes / (1024 * 1024):,.2f} MiB"


def _type_rows(profile: dict[str, Any]) -> str:
    rows = []
    for item in profile["transaction_types"]:
        rate = item["fraud_rows"] / item["rows"]
        rows.append(
            f"| {item['type']} | {_integer(item['rows'])} | "
            f"{_integer(item['fraud_rows'])} | {_percent(rate)} | "
            f"{_number(item['total_amount'])} |"
        )
    return "\n".join(rows)


def _missing_rows(profile: dict[str, Any]) -> str:
    total = profile["overview"]["rows"]
    return "\n".join(
        f"| `{column}` | {_integer(count)} | {_percent(count / total)} |"
        for column, count in profile["missing_values"].items()
    )


def _top_account_rows(items: list[dict[str, Any]]) -> str:
    return "\n".join(
        f"| `{item['account_id']}` | {_integer(item['transactions'])} | "
        f"{_integer(item['fraud_transactions'])} | "
        f"{_number(item['total_amount'])} |"
        for item in items
    )


def _split_rows(splits: dict[str, Any]) -> str:
    rows = []
    for name, payload in splits["splits"].items():
        stats = payload["statistics"]
        rows.append(
            f"| `{name}` | {stats['min_step']}–{stats['max_step']} | "
            f"{_integer(stats['rows'])} | {_integer(stats['fraud_rows'])} | "
            f"{_percent(stats['fraud_rate'])} | "
            f"{_size(payload['artifact']['size_bytes'])} |"
        )
    return "\n".join(rows)


def render_quality_report(
    manifest: dict[str, Any],
    contract: dict[str, Any],
    profile: dict[str, Any],
    splits: dict[str, Any],
) -> str:
    """Return a self-contained Markdown data-quality report."""
    overview = profile["overview"]
    accounts = profile["account_activity"]
    temporal = profile["temporal_activity"]
    duplicates = profile["duplicates"]
    label_relationships = profile["label_relationships"]
    semantic_missingness = profile["semantic_missingness"]
    missing_total = sum(profile["missing_values"].values())
    contract_status = "PASS" if contract["passed"] else "FAIL"

    return f"""# PaySim v0.1 Data-Quality Report

Generated by the reproducible SentinelGraph v0.1 pipeline.

## Executive summary

- Contract status: **{contract_status}**
- Transactions: **{_integer(overview["rows"])}**
- Observed time: steps **{overview["min_step"]}–{overview["max_step"]}**
  ({_integer(temporal["observed_steps"])} hourly steps)
- Fraud labels: **{_integer(overview["fraud_rows"])}**
  ({_percent(overview["fraud_rate"])})
- Missing cells: **{_integer(missing_total)}**
- Exact duplicate rows: **{_integer(duplicates["duplicate_rows"])}**
- Distinct accounts across origin and destination roles:
  **{_integer(accounts["unique_accounts"])}**

The dataset passes the release-blocking structural contract. Its main modelling
risk is not missingness or duplication; it is target leakage from balance and
policy-output fields. PaySim is synthetic, and metrics obtained from it must not
be presented as production fraud performance.

## Source and integrity

| Property | Recorded value |
| --- | --- |
| Dataset | {manifest["dataset"]} |
| Source | [{manifest["dataset_slug"]}]({manifest["source_page"]}) |
| Version | {manifest["dataset_version"]} |
| Dataset license | [{manifest["dataset_license"]}]({manifest["dataset_license_url"]}) |
| Simulator code license | {manifest["simulator_code_license"]} |
| Raw CSV | `{Path(manifest["csv"]["path"]).name}` |
| Raw CSV size | {_integer(manifest["csv"]["size_bytes"])} bytes ({_size(manifest["csv"]["size_bytes"])}) |
| Raw CSV SHA-256 | `{manifest["csv"]["sha256"]}` |
| Archive size | {_integer(manifest["archive"]["size_bytes"])} bytes ({_size(manifest["archive"]["size_bytes"])}) |
| Archive SHA-256 | `{manifest["archive"]["sha256"]}` |
| Checksum verified | {manifest["checksum_verified"]} |

The Kaggle dataset license and the PaySim simulator source-code license are
recorded separately because they govern different artifacts.

## Automated data contract

Release-blocking violations:

| Check | Violations |
| --- | ---: |
{chr(10).join(f"| `{name}` | {_integer(count)} |" for name, count in contract["errors"].items())}

Observed warnings are retained rather than silently cleaned:

| Observation | Rows |
| --- | ---: |
{chr(10).join(f"| `{name}` | {_integer(count)} |" for name, count in contract["warnings"].items())}

Zero-value transactions remain in the source-preserving dataset. They should be
handled explicitly in modelling and investigated as a data slice.
The **{_integer(contract["warnings"]["unexpected_origin_increase"])}**
`unexpected_origin_increase` rows are non-fraud `CASH_OUT` events whose
recorded post-event origin balance exceeds the pre-event balance. This
directional contradiction further supports excluding PaySim balance fields.

## Missing values

| Column | Missing | Rate |
| --- | ---: | ---: |
{_missing_rows(profile)}

There are no syntactically null cells. There is nevertheless source-defined
semantic missingness: **{_integer(semantic_missingness["merchant_destination_rows"])}**
rows have merchant destinations, and all
**{_integer(semantic_missingness["merchant_zero_balance_placeholders"])}** use
zero/zero destination balance placeholders because merchant balances are not
available. A further
**{_integer(semantic_missingness["customer_zero_destination_balances"])}**
customer-destination rows also have zero before/after balances; zeros must not
be globally interpreted as missing.

## Duplicates

- Duplicate groups: **{_integer(duplicates["duplicate_groups"])}**
- Rows beyond the first exact copy: **{_integer(duplicates["duplicate_rows"])}**

Duplicates are defined across all 11 source columns; the generated
`source_row_number` is excluded.

## Fraud labels and transaction types

| Type | Rows | Fraud rows | Fraud rate | Total amount |
| --- | ---: | ---: | ---: | ---: |
{_type_rows(profile)}

The dataset has **{_integer(overview["flagged_rows"])}** policy-flagged rows
({_percent(overview["flagged_rate"])}). `isFlaggedFraud` is not an independent
ground-truth label and is excluded from model features. All
**{_integer(label_relationships["flagged_true_fraud_rows"])}** flags are on
fraud-labelled transfers, while the **{_integer(label_relationships["zero_amount_rows"])}**
zero-amount rows are a different slice: every one is a fraud-labelled
`CASH_OUT`, and none is removed or imputed.

## Account activity

| Metric | Value |
| --- | ---: |
| Unique accounts | {_integer(accounts["unique_accounts"])} |
| Merchant-prefixed accounts | {_integer(accounts["merchant_accounts"])} |
| Origin accounts with more than one originated transaction | {_integer(accounts["repeat_originators"])} |
| Median events per account | {_number(accounts["median_events_per_account"])} |
| p95 events per account | {_number(accounts["p95_events_per_account"])} |
| Maximum events for one account | {_integer(accounts["max_events_per_account"])} |
| Accounts touching a fraud-labelled transaction | {_integer(accounts["accounts_touching_fraud"])} |

### Most active origin accounts

| Account | Transactions | Fraud transactions | Total amount |
| --- | ---: | ---: | ---: |
{_top_account_rows(profile["top_origin_accounts"])}

### Most active destination accounts

| Account | Transactions | Fraud transactions | Total amount |
| --- | ---: | ---: | ---: |
{_top_account_rows(profile["top_destination_accounts"])}

## Temporal and new-account holdouts

The first **{splits["train_fraction_by_observed_time_span"]:.0%}** of the
observed time span is training data. Training ends at step
**{splits["train_end_step_inclusive"]}**; evaluation begins at step
**{splits["future_start_step_inclusive"]}**.

| Artifact | Steps | Rows | Fraud rows | Fraud rate | Size |
| --- | --- | ---: | ---: | ---: | ---: |
{_split_rows(splits)}

`new_account_holdout` is the future-time subset whose origin account was never
seen at or before the training cutoff. It overlaps `future_time_holdout` by
design but never overlaps training. This makes overall future evaluation and
cold-start evaluation directly comparable. In this dataset,
**{_percent(splits["splits"]["new_account_holdout"]["statistics"]["rows"] / splits["splits"]["future_time_holdout"]["statistics"]["rows"])}**
of future rows have an unseen origin account, so the known-account future slice
is too small to treat as the only primary test.

## Leakage assessment

| Field | v0.2 modelling policy | Reason |
| --- | --- | --- |
| `isFraud` | Target only | Ground-truth label. |
| `isFlaggedFraud` | Exclude; rules baseline only | Existing policy output derived from transaction conditions. |
| `oldbalanceOrg`, `oldbalanceDest` | Exclude from PaySim models | Dataset publisher warns the balance state reflects cancelled detected fraud. |
| `newbalanceOrig`, `newbalanceDest` | Prohibit | Post-transaction state and directly leakage-prone. |
| `nameOrig`, `nameDest` | Grouping only | Raw high-cardinality IDs invite entity memorisation; history must be point-in-time. |
| `step` | Splitting/time derivation only | Raw step can proxy simulation regimes and campaigns. |
| `type`, `amount` | Allowed | Known from the transaction request at scoring time. |

The canonical point-in-time table is maintained in
[`DATA_DICTIONARY.md`](DATA_DICTIONARY.md).

## Limitations and release decision

1. PaySim is synthetic and represents one simulated month, not live customer
   behaviour or operational label delay.
2. The fraud injection mechanism and cancellation behaviour can create
   unrealistically easy signals.
3. Account identifiers are synthetic; the new-account rate is not evidence of
   a real deployment's cold-start rate.
4. `new_account_holdout` currently means unseen **origin** account. Destination
   novelty can be reported as a separate slice in a later experiment.
5. The v0.1 data stage is accepted only for leakage-controlled baseline work;
   it does not establish model quality.
"""


def write_quality_report(
    report_path: Path,
    manifest: dict[str, Any],
    contract: dict[str, Any],
    profile: dict[str, Any],
    splits: dict[str, Any],
) -> None:
    """Write the generated Markdown report."""
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(
        render_quality_report(manifest, contract, profile, splits),
        encoding="utf-8",
    )
