"""Integration assertions over generated v0.2 baseline artifacts."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from sentinelgraph.data.provenance import sha256_file

PROJECT_ROOT = Path(__file__).resolve().parents[1]
METRICS_PATH = PROJECT_ROOT / "reports" / "v0.2" / "baseline_metrics.json"


def _metrics() -> dict[str, object]:
    if not METRICS_PATH.exists():
        pytest.skip("metrics are generated by sentinelgraph-baselines")
    payload: dict[str, object] = json.loads(METRICS_PATH.read_text(encoding="utf-8"))
    return payload


@pytest.mark.integration
def test_baseline_metrics_use_temporal_holdouts() -> None:
    metrics = _metrics()
    split = metrics["development_split"]
    assert isinstance(split, dict)
    assert split["development_max_step"] < split["validation_min_step"]
    assert split["validation_max_step"] < split["future_min_step"]


@pytest.mark.integration
def test_all_required_baselines_are_reported() -> None:
    metrics = _metrics()
    models = metrics["models"]
    assert isinstance(models, dict)
    assert set(models) == {
        "dummy_prior",
        "large_transfer_rule",
        "logistic_regression",
        "hist_gradient_boosting",
    }

    prohibited = metrics["prohibited_model_fields"]
    assert isinstance(prohibited, list)
    assert "isFraud" in prohibited
    assert "isFlaggedFraud" in prohibited
    assert "newbalanceOrig" in prohibited


@pytest.mark.integration
def test_learned_validation_thresholds_respect_fpr_budget() -> None:
    metrics = _metrics()
    maximum_fpr = metrics["target_maximum_fpr"]
    assert isinstance(maximum_fpr, float)
    models = metrics["models"]
    assert isinstance(models, dict)
    for name in ("logistic_regression", "hist_gradient_boosting"):
        model = models[name]
        assert isinstance(model, dict)
        evaluation = model["evaluation"]
        assert isinstance(evaluation, dict)
        validation = evaluation["validation"]
        assert isinstance(validation, dict)
        assert validation["false_positive_rate"] <= maximum_fpr


@pytest.mark.integration
def test_model_files_match_recorded_checksums_when_present() -> None:
    metrics = _metrics()
    models = metrics["models"]
    assert isinstance(models, dict)
    artifact_paths = []
    for model in models.values():
        assert isinstance(model, dict)
        artifact = model["artifact"]
        assert isinstance(artifact, dict)
        artifact_paths.append(PROJECT_ROOT / str(artifact["path"]))
    if not all(path.exists() for path in artifact_paths):
        pytest.skip("model artifacts are generated by sentinelgraph-baselines")

    for model in models.values():
        assert isinstance(model, dict)
        artifact = model["artifact"]
        assert isinstance(artifact, dict)
        path = PROJECT_ROOT / str(artifact["path"])
        assert path.stat().st_size == artifact["size_bytes"]
        assert sha256_file(path) == artifact["sha256"]
