"""Integration assertions over generated v0.3 experiment artifacts."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from sentinelgraph.data.provenance import sha256_file

PROJECT_ROOT = Path(__file__).resolve().parents[1]
METRICS_PATH = PROJECT_ROOT / "reports" / "v0.3" / "behavioural_metrics.json"
MANIFEST_PATH = (
    PROJECT_ROOT / "data" / "metadata" / "behavioural_feature_manifest.json"
)


def _load_or_skip(path: Path) -> dict[str, object]:
    if not path.exists():
        pytest.skip(f"{path.name} is generated by sentinelgraph-behaviour")
    payload: dict[str, object] = json.loads(path.read_text(encoding="utf-8"))
    return payload


@pytest.mark.integration
def test_feature_manifest_records_strict_past_contract() -> None:
    manifest = _load_or_skip(MANIFEST_PATH)
    history = manifest["history_contract"]
    assert isinstance(history, dict)
    assert history["window_upper_bound_steps"] == -1
    assert history["same_step_events_excluded"] is True
    assert history["identifiers_emitted_as_features"] is False


@pytest.mark.integration
def test_v03_metrics_preserve_temporal_boundaries() -> None:
    metrics = _load_or_skip(METRICS_PATH)
    split = metrics["development_split"]
    assert isinstance(split, dict)
    assert split["development_max_step"] < split["validation_min_step"]
    assert split["validation_max_step"] < split["future_min_step"]


@pytest.mark.integration
def test_v03_reports_required_models_and_fpr_contract() -> None:
    metrics = _load_or_skip(METRICS_PATH)
    models = metrics["models"]
    assert isinstance(models, dict)
    assert set(models) == {
        "isolation_forest",
        "behavioural_hist_gradient_boosting",
        "behavioural_anomaly_hist_gradient_boosting",
    }
    maximum_fpr = metrics["target_maximum_fpr"]
    assert isinstance(maximum_fpr, float)
    for payload in models.values():
        assert isinstance(payload, dict)
        evaluation = payload["evaluation"]
        assert isinstance(evaluation, dict)
        validation = evaluation["validation"]
        assert isinstance(validation, dict)
        assert validation["false_positive_rate"] <= maximum_fpr


@pytest.mark.integration
def test_v03_model_files_match_checksums_when_present() -> None:
    metrics = _load_or_skip(METRICS_PATH)
    models = metrics["models"]
    assert isinstance(models, dict)
    artifacts = [
        payload["artifact"]
        for payload in models.values()
        if isinstance(payload, dict)
    ]
    paths = [
        PROJECT_ROOT / str(artifact["path"])
        for artifact in artifacts
        if isinstance(artifact, dict)
    ]
    if not paths or not all(path.exists() for path in paths):
        pytest.skip("v0.3 model artifacts are generated locally")

    for artifact, path in zip(artifacts, paths, strict=True):
        assert isinstance(artifact, dict)
        assert path.stat().st_size == artifact["size_bytes"]
        assert sha256_file(path) == artifact["sha256"]
