"""Integration assertions over generated v0.4 graph artifacts."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from sentinelgraph.data.provenance import sha256_file

PROJECT_ROOT = Path(__file__).resolve().parents[1]
METRICS_PATH = PROJECT_ROOT / "reports" / "v0.4" / "graph_metrics.json"
MANIFEST_PATH = PROJECT_ROOT / "data" / "metadata" / "graph_feature_manifest.json"


def _load_or_skip(path: Path) -> dict[str, object]:
    if not path.exists():
        pytest.skip(f"{path.name} is generated by sentinelgraph-graph")
    payload: dict[str, object] = json.loads(path.read_text(encoding="utf-8"))
    return payload


@pytest.mark.integration
def test_graph_manifest_records_strict_past_contract() -> None:
    manifest = _load_or_skip(MANIFEST_PATH)
    history = manifest["history_contract"]
    assert isinstance(history, dict)
    assert history["window_upper_bound_steps"] == -1
    assert history["same_step_edges_excluded"] is True
    assert history["labels_used_in_graph_features"] is False
    assert history["identifiers_emitted_as_features"] is False


@pytest.mark.integration
def test_graph_topology_matches_paysim_constraints() -> None:
    manifest = _load_or_skip(MANIFEST_PATH)
    topology = manifest["topology"]
    components = manifest["components"]
    assert isinstance(topology, dict)
    assert isinstance(components, dict)
    assert topology["edge_count"] == 6_362_620
    assert topology["unique_directed_pair_count"] == topology["edge_count"]
    assert topology["repeated_directed_pair_count"] == 0
    assert topology["reciprocal_pair_count"] == 0
    assert components["cycle_rank"] == 0


@pytest.mark.integration
def test_v04_metrics_preserve_temporal_boundaries_and_fpr() -> None:
    metrics = _load_or_skip(METRICS_PATH)
    split = metrics["development_split"]
    assert isinstance(split, dict)
    assert split["development_max_step"] < split["validation_min_step"]
    assert split["validation_max_step"] < split["future_min_step"]

    models = metrics["models"]
    maximum_fpr = metrics["target_maximum_fpr"]
    assert isinstance(models, dict)
    assert isinstance(maximum_fpr, float)
    assert set(models) == {
        "behavioural_reference",
        "graph_only_hist_gradient_boosting",
        "behavioural_graph_hist_gradient_boosting",
    }
    for payload in models.values():
        assert isinstance(payload, dict)
        validation = payload["evaluation"]["validation"]
        assert validation["false_positive_rate"] <= maximum_fpr


@pytest.mark.integration
def test_v04_model_files_match_checksums_when_present() -> None:
    metrics = _load_or_skip(METRICS_PATH)
    models = metrics["models"]
    assert isinstance(models, dict)
    artifacts = [
        payload["artifact"]
        for payload in models.values()
        if isinstance(payload, dict)
    ]
    paths = [
        PROJECT_ROOT / str(artifact["path"])
        for artifact in artifacts
        if isinstance(artifact, dict)
    ]
    if not paths or not all(path.exists() for path in paths):
        pytest.skip("v0.4 model artifacts are generated locally")

    for artifact, path in zip(artifacts, paths, strict=True):
        assert isinstance(artifact, dict)
        assert path.stat().st_size == artifact["size_bytes"]
        assert sha256_file(path) == artifact["sha256"]
