"""Integration assertions over generated v0.1 metadata."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from sentinelgraph.data.provenance import EXPECTED_CSV_SHA256, sha256_file

PROJECT_ROOT = Path(__file__).resolve().parents[1]
METADATA_DIR = PROJECT_ROOT / "data" / "metadata"


def _load_or_skip(name: str) -> dict[str, object]:
    path = METADATA_DIR / name
    if not path.exists():
        pytest.skip(f"{name} is generated by sentinelgraph-data all")
    payload: dict[str, object] = json.loads(path.read_text(encoding="utf-8"))
    return payload


@pytest.mark.integration
def test_generated_dataset_manifest_is_verified() -> None:
    manifest = _load_or_skip("dataset_manifest.json")
    csv_record = manifest["csv"]
    assert isinstance(csv_record, dict)
    assert csv_record["sha256"] == EXPECTED_CSV_SHA256
    assert manifest["checksum_verified"] is True


@pytest.mark.integration
def test_generated_contract_passes() -> None:
    contract = _load_or_skip("contract_results.json")
    assert contract["passed"] is True
    errors = contract["errors"]
    assert isinstance(errors, dict)
    assert all(count == 0 for count in errors.values())


@pytest.mark.integration
def test_split_artifacts_match_manifest() -> None:
    manifest = _load_or_skip("split_manifest.json")
    splits = manifest["splits"]
    assert isinstance(splits, dict)

    artifact_paths = [
        PROJECT_ROOT / str(payload["artifact"]["path"])
        for payload in splits.values()
        if isinstance(payload, dict) and isinstance(payload.get("artifact"), dict)
    ]
    if not artifact_paths or not all(path.exists() for path in artifact_paths):
        pytest.skip("processed split artifacts are generated by sentinelgraph-data all")

    train = splits["train"]
    future = splits["future_time_holdout"]
    new_account = splits["new_account_holdout"]
    assert isinstance(train, dict)
    assert isinstance(future, dict)
    assert isinstance(new_account, dict)
    assert train["statistics"]["max_step"] < future["statistics"]["min_step"]
    assert new_account["statistics"]["rows"] <= future["statistics"]["rows"]

    for payload in splits.values():
        assert isinstance(payload, dict)
        artifact = payload["artifact"]
        assert isinstance(artifact, dict)
        path = PROJECT_ROOT / str(artifact["path"])
        assert path.exists()
        assert path.stat().st_size == artifact["size_bytes"]
        assert sha256_file(path) == artifact["sha256"]
